name: Dockerized Service
on: [push]
jobs:
  build_and_deploy_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Copy docker compose file
        run: scp -i "${{secrets.KEY}}" docker-compose.yml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }} 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:app"
          push: true
          tags: | 
            ${{ secrets.DOCKERHUB_USERNAME }}/dockerized-service:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/dockerized-service:latest
  run_container:
    needs: build_and_deploy_docker_image
    runs-on: ubuntu-latest
    steps: 
      - name: Pull and run container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: docker compose up